### ISSUE TITLE
realpath error

### ISSUE THREAD

**Issue by muralikodali** [uriel1998/ppl_virdirsyncer_addysearch#1]
script giving following error :  

realpath: invalid option -- 'p'
Try 'realpath --help' for more information.
No matches found!

**Comment by uriel1998** [comment]
Huh.  What environment/operating system and version of `realpath` are you using?  When I type `realpath -h` I get this (Debian Buster):
```
realpath 1.0.24
usage: realpath [-f file_list] [-h(elp)] [-p(ipe)] [-v(erbose)] file...
```

Even if I issue that command by itself, it just waits for the pipe.  [And then I find a manpage that lists other switches](https://www.man7.org/linux/man-pages/man1/realpath.1.html)... argh.  Let me see what I can figure out.  Thanks!

**Comment by uriel1998** [comment]
Okay, I'm still interested in the environment (email me if you can't comment after the close), but I just pushed a fix that moves the variable and seems to work without the -p switch on realpath.  Let me know if you have more issues!

**Comment by muralikodali** [comment]
i have tried the following command which gave correct output.
```
rg "FN:" /home/murali/.pim//contacts/* | awk -F ':' '{print $3 ":" $1 }' | rofi -i -dmenu -p "Whose Vcard?" | awk -F ':' '{print $2}'

/home/murali/.pim/contacts/lgg/1a469e60-c153-4f96-93bc-6509bdaf070a.vcf
```
but realpath has some issue. i am using arch linux with realpath from gnu coreutils (https://www.gnu.org/software/coreutils/realpath)

![20201014T1054-screenshot](https://user-images.githubusercontent.com/11482766/95947260-d8d1f680-0e0b-11eb-9405-5b1d94932813.png)


vcardreader.sh gave correct output for the first attempt. afterwards it's output is empty.

**Comment by ronnac** [comment]
@uriel1998 you also need to fix this in vcardreader.sh
replace 
`... | realpath -p`
by
`... | xargs realpath`

**Comment by muralikodali** [comment]
thanks @uriel1998 for your advice.

now the program is able catch the file name. but contents of some vcards are displayed well and some vcards are not showing any details.
